# Generated by Django 3.0.8 on 2020-08-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.CharField(max_length=15)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('MobileNumber', models.IntegerField()),
                ('Categery', models.CharField(choices=[('General', 'General'), ('Obc', 'Obc'), ('Other', 'Other')], max_length=20)),
                ('Income', models.CharField(choices=[('Upto one lakh', 'Upto one lakh'), ('More than one lakh', 'More than one lakh')], max_length=20)),
                ('MotherName', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('FatherOccupation', models.CharField(max_length=50)),
                ('AlternaterContactNo', models.IntegerField()),
                ('Alternateemail', models.CharField(max_length=50)),
                ('CorrespondingAddress', models.CharField(max_length=100)),
                ('PermanentAddress', models.CharField(max_length=100)),
                ('BoardOfEducation', models.CharField(max_length=50)),
                ('BoardRollNo', models.CharField(max_length=15)),
                ('YearOfPassing', models.CharField(max_length=4)),
                ('Mathematics', models.CharField(max_length=8)),
                ('Physics', models.CharField(max_length=8)),
                ('Chemistry', models.CharField(max_length=8)),
                ('Total', models.CharField(max_length=8)),
                ('Percentage', models.CharField(max_length=8)),
                ('Coures', models.CharField(choices=[('B.Tech(Electronics & communication Engineering(ECE))', 'B.Tech(Electronics & communication Engineering(ECE))'), ('B.Tech(Electrial & Electronics Engineering(EN))', 'B.Tech(Electrial & Electronics Engineering(EN))'), ('B.Tech(Mechanical Engineering(ME))', 'B.Tech(Mechanical Engineering(ME))'), ('B.Tech(Computer Science & Engineering(CSE))', 'B.Tech(Computer Science & Eng,ineering(CSE))'), ('B.Tech(Information Technology (IT))', 'B.Tech(Information Technology (IT))'), ('B.Tech(Civil Engineering(CE))', 'B.Tech(Civil Engineering(CE))'), ('B.Tech(Electrical Engineering(EE))', 'B.Tech(Electrical Engineering(EE))'), ('B.Pharma', 'B.Pharma'), ('D.Pharma', 'D.Pharma')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cemail', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('msgcont', models.CharField(max_length=150)),
            ],
        ),
    ]
